.* ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
.* บ  FILENAME:      PMED.INC                                         mm/dd/yy     บ
.* บ                                                                               บ
.* บ  DESCRIPTION:   Help Panel Symbol definitions for PMED                        บ
.* บ                                                                               บ
.* บ  NOTES:                                                                       บ
.* บ                                                                               บ
.* บ  PROGRAMMER:    Uri Joseph Stern and James Stan Morrow                        บ
.* บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for Power Programmers          บ
.* บ                                                                               บ
.* บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ
.* บ                                                                               บ
.* ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
.*
.* NOTE: These definitions must match those defined for the help panels
.*       in PMED.H.

.nameit symbol=HID_GENERAL   text='10'
.nameit symbol=HID_FILE_MENU text='100'
.nameit symbol=HID_FILE_NEW  text='101'
.nameit symbol=HID_FILE_OPEN text='102'
.nameit symbol=HID_FILE_SAVE text='103'
.nameit symbol=HID_FILE_SAVEAS text='104'
.nameit symbol=HID_FILE_EXIT text='199'
.nameit symbol=HID_HELP_MENU text='200'
.nameit symbol=HID_HELP_GEN  text='201'
.nameit symbol=HID_HELP_USE  text='202'
.nameit symbol=HID_HELP_KEYS text='203'
.nameit symbol=HID_HELP_PROD text='299'
.nameit symbol=HID_KEYS_HELP text='5000'
.nameit symbol=HID_NOT_SAVED text='5001'
