// ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
// บ  FILENAME:      PMEDDLG.H                                        mm/dd/yy     บ
// บ                                                                               บ
// บ  DESCRIPTION:   Definitions for PMED Dialog boxes and items                   บ
// บ                                                                               บ
// บ  NOTES:                                                                       บ
// บ                                                                               บ
// บ  PROGRAMMER:    Uri Joseph Stern and James Stan Morrow                        บ
// บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for Power Programmers          บ
// บ                                                                               บ
// บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ
// บ                                                                               บ
// ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

#define DLGID_PRODINFO              101
#define DID_PRODICON                110
#define DID_NOTSAVED                200
#define DID_ICON                    201
#define DID_MESSAGE                 202
#define DID_DISCARD                 203
#define DID_HELP                    204
