// ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
// บ  FILENAME:      GDATA.H                                          mm/dd/yy     บ
// บ                                                                               บ
// บ  DESCRIPTION:   Global Data for PMSCREEN and PMHOOKS                          บ
// บ                                                                               บ
// บ  NOTES:         This file contains all of the data that is needed to be       บ
// บ                 global for both the EXE and DLL modules.                      บ
// บ                                                                               บ
// บ  PROGRAMMER:    Uri Joseph Stern and James Stan Morrow                        บ
// บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for Power Programmers          บ
// บ                                                                               บ
// บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ
// บ                                                                               บ
// ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

// --------------------------------------------------------------------------                               
// Miscellaneous definitions
// --------------------------------------------------------------------------                               
#define MODULE_HOOKS     "PMHOOKS"                
#define CLASSNAME        "PM_Screen"

// --------------------------------------------------------------------------                               
// User defined messages.                                                                                       
// --------------------------------------------------------------------------                               
#define WM_UPDATEBITMAP  WM_USER + 20
#define WM_LOCKUP        WM_USER + 21
