#  ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
#  บ  FILENAME:      MAKEFILE                                         mm/dd/yy     บ
#  บ                                                                               บ
#  บ  DESCRIPTION:   Build Script for PMSCREEN/Chapter 17 Sample Program           บ
#  บ                                                                               บ
#  บ  NOTES:         Instructions for building the program.                        บ
#  บ                                                                               บ
#  บ  PROGRAMMER:    Uri Joseph Stern and James Stan Morrow                        บ
#  บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for Power Programmers          บ
#  บ                                                                               บ
#  บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ
#  บ                                                                               บ
#  ฬอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
#  บ                                                                               บ
#  บ                            Compiler Options                                   บ
#  ฬอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
#  บ                                                                               บ
#  บ  /C      Compile only, do not link                                            บ
#  บ  /Q      Do NOT display Compiler Logo Information (Who needs it??)            บ
#  บ  /Ss     Allow Double-Slash (//) Comments                                     บ
#  บ  /Ti     Generate debug information                                           บ
#  บ  /Gm     Link with the Multi-Threaded Library                                 บ
#  บ  /W3     Compile with Warning Level 3 Invoked                                 บ
#  บฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤบ
#  บ  /O+     Optimize Code                                                        บ
#  บ  /Ti-    Do NOT generate debug information                                    บ
#  บ  /Gs-    Do NOT remove Stack Probes                                           บ
#  บ  /Sa     Strict ANSI Conformance                                              บ
#  บ  /Ge-    Build a DLL                                                          บ
#  ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

#  --------------------------------------------------------------------------
#  Define source file types to consider
#  --------------------------------------------------------------------------
.SUFFIXES:
.SUFFIXES: .c .rc

# --------------------------------------------------------------------------          
# Define the object files that will be built by the compile.                          
# --------------------------------------------------------------------------          
OBJECT1 = pmscreen.obj                                                                
OBJECT2 = clipbrd.obj                                                                 
COMMON  = shcommon.obj                                                                

EXECUTABLE = PMSCREEN.EXE            
DLL        = PMHOOKS.DLL             
RESOURCE   = PMSCREEN.RES            
HELPFILE   = PMSCREEN.HLP            
MAPFILE    = PMSCREEN.MAP            
DEFFILE    = PMSCREEN.DEF            

#  --------------------------------------------------------------------------
#  Target for building all components of the application
#  --------------------------------------------------------------------------
ALL: $(EXECUTABLE) $(DLL)

#  --------------------------------------------------------------------------
#  Target for building the tutorial control dynamic link library
#  --------------------------------------------------------------------------
pmhooks.dll: pmhooks.obj pmhooks.def makefile
   ICC.EXE @<<
 /B" /de /pmtype:pm /nologo /m:full"
 /Fe"pmhooks.dll"
pmhooks.obj
$(COMMON)
pmhooks.def
<<
   MAPSYM pmhooks.map                       

# --------------------------------------------------------------------------           
# Instructions for building the program executable                                     
# --------------------------------------------------------------------------           
$(EXECUTABLE): $(OBJECT1) $(OBJECT2) $(COMMON) $(RESOURCE)                  
   ICC.EXE @<<                                                                         
 /B" /de /nologo /m:full"                                                              
 /Fe"$(EXECUTABLE)" /Fm"$(MAPFILE)" $(DEFFILE)                                         
$(OBJECT1)                                                                             
$(OBJECT2)                                                                             
$(COMMON)                                                                              
<<                                                                                     
   rc -r pmscreen.rc 
   RC $(RESOURCE) $(EXECUTABLE)                               
   MAPSYM $(MAPFILE)                       


SHCOMMON.OBJ: ..\COMMON\SHCOMMON.C SHCOMMON.H MAKEFILE                 
   COPY ..\COMMON\SHCOMMON.C                                           
   ICC.EXE /Sa /Ss /Q /Ti /Gm /C   .\SHCOMMON.c                        
   DEL SHCOMMON.C                                                      



#  --------------------------------------------------------------------------
#  generic build rules
#  --------------------------------------------------------------------------
{.}.rc.res:                     
   RC -r $*.RC                  

{.}.c.obj:
   ICC.EXE /Ss /Q /Ti /Gm /C   .\$*.c

# --------------------------------------------------------------------------      
# Define dependencies for the applications build targets                          
# --------------------------------------------------------------------------      
$(RESOURCE):  pmscreen.rc pmscreen.h pmscreen.ico                                 
                                                                                  
$(OBJECT1):   pmscreen.c pmscreen.h pmscreen.fnc pmhooks.h gdata.h                
$(OBJECT2):   clipbrd.c shcommon.h                                      

pmhooks.obj:  pmhooks.c pmhooks.h gdata.h shcommon.h                  
   ICC.EXE /Ss /Q /Ti /Ge- /C   .\$*.c              

