// ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
// บ  FILENAME:      PMSTATS.H                                        mm/dd/yy     บ
// บ                                                                               บ
// บ  DESCRIPTION:   Primary Include File for PMSTATS                              บ
// บ                                                                               บ
// บ  NOTES:         This file contains all of the various defines for all of      บ
// บ                 window identifies and numeric string identifiers.             บ
// บ                                                                               บ
// บ  PROGRAMMER:    Uri Joseph Stern and James Stan Morrow                        บ
// บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for the Power Programmer       บ                   
// บ                                                                               บ
// บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ
// บ                                                                               บ
// ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

// --------------------------------------------------------------------------          
// Define our window identifiers                                                     
// --------------------------------------------------------------------------          
#define ID_FRAME         1
#define ID_STATIC        2

// --------------------------------------------------------------------------          
// Define our dialog identifiers                                                     
// --------------------------------------------------------------------------          
#define IDD_PRODINFO       50                 
#define IDD_SPREADSHEET    51

// --------------------------------------------------------------------------          
// File Submenu
// --------------------------------------------------------------------------          
#define ID_FILEMENU       100
#define IDM_ENTERSTATS    101
#define IDM_PRODINFO      102

// --------------------------------------------------------------------------          
// Help Submenu
// --------------------------------------------------------------------------          
#define ID_HELPMENU       103
#define IDM_HELPGEN       104         
#define IDM_HELPKEYS      105


#define IDC_PRODUCTS      110                 
#define MLE_SPYWINDOW     111                 



#define IDB_PRODINFO      208          
#define IDB_OS2TILE       209

// --------------------------------------------------------------------------                       
// Entryfield Identifiers                                                                                 
// --------------------------------------------------------------------------                       
#define IDE_MONTH01       401            
#define IDE_MONTH02       402            
#define IDE_MONTH03       403            
#define IDE_MONTH04       404            
#define IDE_MONTH05       405            
#define IDE_MONTH06       406            
#define IDE_MONTH07       407                  
#define IDE_MONTH08       408            
#define IDE_MONTH09       409            
#define IDE_MONTH10       410            
#define IDE_MONTH11       411            
#define IDE_MONTH12       412            
#define IDE_MONTH13       413

#define DID_HELP          500

