#  ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
#  บ  FILENAME:      MAKEFILE                                         mm/dd/yy     บ
#  บ                                                                               บ
#  บ  DESCRIPTION:   Build Script for TUTORIAL/Chapter 14 Sample Program           บ
#  บ                                                                               บ
#  บ  NOTES:         Instructions for building the program.                        บ
#  บ                                                                               บ
#  บ  PROGRAMMER:    Uri Joseph Stern and James Stan Morrow                        บ
#  บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for Power Programmers          บ
#  บ                                                                               บ
#  บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ
#  บ                                                                               บ
#  ฬอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
#  บ                                                                               บ
#  บ                            Compiler Options                                   บ
#  ฬอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
#  บ                                                                               บ
#  บ  /C      Compile only, do not link                                            บ
#  บ  /Q      Do NOT display Compiler Logo Information (Who needs it??)            บ
#  บ  /Ss     Allow Double-Slash (//) Comments                                     บ
#  บ  /Ti     Generate debug information                                           บ
#  บ  /Gm     Link with the Multi-Threaded Library                                 บ
#  บ  /W3     Compile with Warning Level 3 Invoked                                 บ
#  บฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤบ
#  บ  /O+     Optimize Code                                                        บ
#  บ  /Ti-    Do NOT generate debug information                                    บ
#  บ  /Gs-    Do NOT remove Stack Probes                                           บ
#  บ  /Sa     Strict ANSI Conformance                                              บ
#  บ  /Ge-    Build a DLL                                                          บ
#  ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

#  --------------------------------------------------------------------------
#  Define source file types to consider
#  --------------------------------------------------------------------------
.SUFFIXES:
.SUFFIXES: .c .rc

#  --------------------------------------------------------------------------
#  Target for building all components of the application
#  --------------------------------------------------------------------------
ALL: tutorial.dll tutorial.lib tutor.exe                        

#  --------------------------------------------------------------------------
#  Target for building the tutorial control dynamic link library
#  --------------------------------------------------------------------------
tutorial.dll: tutorial.obj tutorial.def makefile
   ICC.EXE @<<
 /B" /de /pmtype:pm /nologo /m:full"
 /Fe"tutorial.dll"
tutorial.obj
tutorial.def
<<

#  --------------------------------------------------------------------------
#  Target for building the tutorial control import library
#  --------------------------------------------------------------------------
tutorial.lib: tutorial.def makefile
   implib tutorial.lib tutorial.def

#  --------------------------------------------------------------------------
#  Target for building the application executable
#  --------------------------------------------------------------------------
tutor.exe: tutor.obj tutor.res makefile
   ICC.EXE @<<
 /B" /de /pmtype:pm /nologo /m:full"
 /Fe"tutor.exe"
tutor.obj
tutorial.lib
<<
   RC tutor.res tutor.exe

#  --------------------------------------------------------------------------
#  generic build rules
#  --------------------------------------------------------------------------
{.}.rc.res:
   RC -r .\$*.RC

{.}.c.obj:
   ICC.EXE /Ss /Q /Ti /Gm /C   .\$*.c

#  --------------------------------------------------------------------------
#  Specific targets
#  --------------------------------------------------------------------------
tutor.res: makefile

tutor.obj: tutorial.h makefile

tutorial.obj: tutorial.h makefile
   ICC.EXE /Ss /Q /Ti /Ge- /C   .\$*.c
