.* ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
.* บ  FILENAME:      THREADS.INC                                      mm/dd/yy     บ
.* บ                                                                               บ
.* บ  DESCRIPTION:   Help Panel Symbol definitions for THREADS                     บ
.* บ                                                                               บ
.* บ  NOTES:         None                                                          บ
.* บ                                                                               บ
.* บ  PROGRAMMER:    Uri Joseph Stern and James Stan Morrow                        บ
.* บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for Power Programmers          บ
.* บ                                                                               บ
.* บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ
.* บ                                                                               บ
.* ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
.*
.* NOTE: These definitions must match those defined for the help panels
.*       in THREADS.H

.nameit symbol=HID_GENHELP        text='100'
.nameit symbol=HID_FILE           text='200'
.nameit symbol=HID_FILEINITIALIZE text='201'
.nameit symbol=HID_FILEDELETE     text='202'
.nameit symbol=HID_FILEEXIT       text='203'
.nameit symbol=HID_MODE           text='300'
.nameit symbol=HID_MODESINGLE     text='301'
.nameit symbol=HID_MODEPEEK       text='302'
.nameit symbol=HID_MODEMULT       text='303'
.nameit symbol=HID_MODEOBJ        text='304'
.nameit symbol=HID_HELP           text='400'
.nameit symbol=HID_HELPGENERAL    text='401'
.nameit symbol=HID_HELPUSING      text='402'
.nameit symbol=HID_HELPPRODINFO   text='403'
