// ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป                   
// บ  FILENAME:      SHERROR.H                                        mm/dd/yy     บ                   
// บ                                                                               บ                   
// บ  DESCRIPTION:   Header file for symbolic information and definitions.         บ                   
// บ                                                                               บ                   
// บ  NOTES:         This file contains the various numeric return codes that      บ                   
// บ                 can be returned by SHOWOFF functions.                         บ                   
// บ                                                                               บ                   
// บ  PROGRAMMER:    Uri Joseph Stern                                              บ                   
// บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for Power Programmers          บ                   
// บ                                                                               บ                   
// บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ                   
// บ                                                                               บ                   
// ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ                   
 
// --------------------------------------------------------------------------            
// Miscellaneous Error Codes
// --------------------------------------------------------------------------            
#define ERROR_OPENING_FILE             101                  
#define ERROR_INVALID_BITMAP           102                  
#define ERROR_CREATING_BITMAP          103                  
#define ERROR_ALLOC_MEM                104                  
#define ERROR_READING_FILE             105
#define ERROR_WRITING_PROFILE          106
#define ERROR_BOGUS_HPS                107
