// ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
// บ  FILENAME:      SUBCLASS.H                                       mm/dd/yy     บ
// บ                                                                               บ
// บ  DESCRIPTION:   Main header File for SUBCLASS/Chapter 10 Sample Program       บ
// บ                                                                               บ
// บ  NOTES:         Header File                                                   บ
// บ                                                                               บ
// บ  PROGRAMMER:    Uri Joseph Stern and James Stan Morrow                        บ
// บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for Power Programmers          บ
// บ                                                                               บ
// บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ
// บ                                                                               บ
// ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

// --------------------------------------------------------------------------
// Define window and resource id for the main application window
// --------------------------------------------------------------------------
#define  APPLICATION_ID          100

// --------------------------------------------------------------------------
// Define menu item IDs
// --------------------------------------------------------------------------
#define  MID_EDIT                1000
#define  MID_F1                  1100
#define  MID_F2                  1101
#define  MID_F3                  1102
#define  MID_F4                  1103
#define  MID_HELP                1104
#define  MID_HELPGEN             1105
#define  MID_HELPKEYS            1106
#define  MID_PRODINFO            1107

// --------------------------------------------------------------------------      
// Define resources for product information dialog                 
// --------------------------------------------------------------------------      
#define IDD_PRODINFO             1150 
#define IDB_PRODINFO             1151 

#define HELP_TEXT     \                                                                            
"Single click the right mouse button on any of the static text fields below"\             
" or select any of the options from the edit menu to see how we subclassed the"\             
" static text control to create an editable static text control."
