#  ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
#  บ  FILENAME:      MAKEFILE                                         mm/dd/yy     บ
#  บ                                                                               บ
#  บ  DESCRIPTION:   Build Script for MATCH/Chapter 13 Sample Program              บ
#  บ                                                                               บ
#  บ  NOTES:         Instructions for building the program.                        บ
#  บ                 To build this sample program you need to have MMPM installed  บ
#  บ                 for the MMPM2.LIB library.                                    บ
#  บ                                                                               บ
#  บ  PROGRAMMER:    Uri Joseph Stern and James Stan Morrow                        บ
#  บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for Power Programmers          บ
#  บ                                                                               บ
#  บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ
#  บ                                                                               บ
#  ฬอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน                
#  บ                                                                               บ                
#  บ                            Compiler Options                                   บ                
#  ฬอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน                
#  บ                                                                               บ
#  บ  /C      Compile only, do not link                                            บ                
#  บ  /Q      Do NOT display Compiler Logo Information (Who needs it??)            บ                
#  บ  /Ss     Allow Double-Slash (//) Comments                                     บ                
#  บ  /Ti     Generate debug information                                           บ                
#  บ  /Gm     Link with the Multi-Threaded Library                                 บ                
#  บ  /W3     Compile with Warning Level 3 Invoked                                 บ                
#  บฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤบ
#  บ  /O+     Optimize Code                                                        บ                
#  บ  /Ti-    Do NOT generate debug information                                    บ                
#  บ  /Gs-    Do NOT remove Stack Probes                                           บ                
#  บ  /Sa     Strict ANSI Conformance                                              บ                
#  บ  /Ge-    Build a DLL                                                          บ                
#  ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ                

# --------------------------------------------------------------------------      
# Define the compiler and compiler flags to be used.                              
# --------------------------------------------------------------------------      
COMPILER = ICC                                                          
CFLAGS   = /C /Q /Ss /Ti /Gm /W3              

# --------------------------------------------------------------------------
# Define source file types processed by this file.
# --------------------------------------------------------------------------
.SUFFIXES: .c .rc .ipf

# --------------------------------------------------------------------------          
# Define the object files that will be built by the compile.                                 
# --------------------------------------------------------------------------          
OBJECT1 = match.obj       
COMMON  = shcommon.obj                   
MMPMLIB = mmpm2.lib

EXECUTABLE = MATCH.EXE
RESOURCE   = MATCH.RES
MAPFILE    = MATCH.MAP
DEFFILE    = MATCH.DEF

# --------------------------------------------------------------------------
# Define main build target - which builds everything
# --------------------------------------------------------------------------
ALL: $(EXECUTABLE) $(RESOURCE) 

# --------------------------------------------------------------------------
# Instructions for building the program executable
# --------------------------------------------------------------------------
$(EXECUTABLE): $(OBJECT1) $(COMMON) $(RESOURCE) 
   ICC.EXE @<<
 /B" /de /nologo /m:full"
 /Fe"$(EXECUTABLE)" /Fm"$(MAPFILE)" $(DEFFILE)
$(OBJECT1)
$(COMMON)
$(MMPMLIB)            
<<
   RC $(RESOURCE) $(EXECUTABLE)
   MAPSYM $(MAPFILE)

# --------------------------------------------------------------------------
# Generic rule for generating a .RES file from a .RC file
# --------------------------------------------------------------------------
{.}.rc.res:
   RC -r $*.RC

# --------------------------------------------------------------------------
# Generic rule for generating a .OBJ file from a .C file
# --------------------------------------------------------------------------
{.}.c.obj:
   $(COMPILER) $(CFLAGS) *.c

# --------------------------------------------------------------------------
# Specific rule for generating SHCOMMON.OBJ since the source is in a
# separate directory - causing problems for current version of NMAKE
# --------------------------------------------------------------------------
SHCOMMON.OBJ: ..\COMMON\SHCOMMON.C SHCOMMON.H MAKEFILE
   COPY ..\COMMON\SHCOMMON.C
   ICC.EXE /Sa /Ss /Q /Ti /Gm /C   .\SHCOMMON.c
   DEL SHCOMMON.C

# --------------------------------------------------------------------------
# Define dependencies for the applications build targets
# --------------------------------------------------------------------------
$(RESOURCE):  match.rc match.h match.ico           

$(OBJECT1):   match.c match.h                                      
