// ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
// บ  FILENAME:      MATCH.H                                          mm/dd/yy     บ
// บ                                                                               บ
// บ  DESCRIPTION:   Primary Include File for CLKDRAW                              บ
// บ                                                                               บ
// บ  NOTES:         This file contains all of the various defines for all of      บ
// บ                 window identifies and numeric string identifiers.             บ
// บ                                                                               บ
// บ  PROGRAMMER:    Uri Joseph Stern and James Stan Morrow                        บ
// บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for Power Programmers          บ
// บ                                                                               บ
// บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ
// บ                                                                               บ
// ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ



// --------------------------------------------------------------------------
// Main Window Identifier       
// --------------------------------------------------------------------------
#define ID_MAINWND      1000              

// --------------------------------------------------------------------------
// Presentation Parameters       
// --------------------------------------------------------------------------
#define PP_PROGTITLE PRESPARAMS PP_FOREGROUNDCOLORINDEX, CLR_RED PRESPARAMS PP_FONTNAMESIZE, "28.Tms Rmn"

// --------------------------------------------------------------------------
// Window Identifiers            
// --------------------------------------------------------------------------
#define ID_PRODINFO     100

// --------------------------------------------------------------------------
// Product Information Bitmap
// --------------------------------------------------------------------------
#define IDB_PRODINFO    250 

// --------------------------------------------------------------------------
// Action Bar Menu               
// --------------------------------------------------------------------------
#define ID_OPTIONS      1   
#define IDM_START       2
#define IDM_PRODINFO    3


