// ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป               
// บ  FILENAME:      WINCHART.H                                       mm/dd/yy     บ               
// บ                                                                               บ               
// บ  DESCRIPTION:   Primary Header File For the WINCHART / Chapter 09 Program     บ               
// บ                                                                               บ               
// บ  NOTES:         This file contains the various resource definitions used      บ               
// บ                 by the WINCHART source code.                                  บ               
// บ                                                                               บ               
// บ  PROGRAMMER:    Uri Joseph Stern and James Stan Morrow                        บ               
// บ  COPYRIGHTS:    OS/2 Warp Presentation Manager for Power Programmers          บ               
// บ                                                                               บ               
// บ  REVISION DATES:  mm/dd/yy  Created this file                                 บ               
// บ                                                                               บ               
// ศอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ               
#define IDM_CHART           101
#define IDM_PRODINFO        102
#define IDM_EXIT            103

#define ID_STATUSLINE       301
#define ID_APPNAME          302
#define ID_TOPICNAME        303
#define ID_DATA             304

// --------------------------------------------------------------------------   
// Remap these identifiers
// --------------------------------------------------------------------------   
#define DID_OK     IDOK
#define DID_CANCEL IDCANCEL
